//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Functions_lua_txt
    {
        public const string BundleName = "functions_lua_txt";
        public const string FUNCTIONS = "functions";
    }
    public class Main_lua_txt
    {
        public const string BundleName = "main_lua_txt";
        public const string MAIN = "main";
    }
    public class Root_lua_txt
    {
        public const string BundleName = "root_lua_txt";
        public const string ROOT = "root";
    }
    public class Sys_lua_txt
    {
        public const string BundleName = "sys_lua_txt";
        public const string SYS = "sys";
    }
    public class Ui_lua_txt
    {
        public const string BundleName = "ui_lua_txt";
        public const string UI = "ui";
    }
}
