//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Cs_coroutine_lua_txt
    {
        public const string BundleName = "cs_coroutine_lua_txt";
        public const string CS_COROUTINE = "cs_coroutine";
    }
    public class Eventcenter_lua_txt
    {
        public const string BundleName = "eventcenter_lua_txt";
        public const string EVENTCENTER = "eventcenter";
    }
    public class Gameplay2_unity
    {
        public const string BundleName = "gameplay2_unity";
        public const string GAMEPLAY2 = "gameplay2";
    }
    public class Util_lua_txt
    {
        public const string BundleName = "util_lua_txt";
        public const string UTIL = "util";
    }
}
